services:
  - type: web
    name: object-detection-webapp
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      waitress-serve --port=$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7